<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Toolbox</AssemblyName>
    <Copyright>Copyright © Josef Nemec 2026</Copyright>
    <TargetFramework>net462</TargetFramework>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <Platforms>x86</Platforms>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="..\..\..\references\Fonts\icofont.ttf">
      <Link>Templates\Themes\Fonts\icofont.ttf</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\..\references\Fonts\TitilliumWeb*.*">
      <Link>Templates\Themes\Fullscreen\Fonts\%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\..\references\Fonts\PlayStation4.*">
      <Link>Templates\Themes\Fullscreen\Fonts\%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\..\references\Fonts\XBOXONE.*">
      <Link>Templates\Themes\Fullscreen\Fonts\%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="NLog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Templates\**" />
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="Templates\Themes\Desktop\Fonts\" />
  </ItemGroup>
  
  <ItemGroup>
    <None Include="..\..\Playnite.DesktopApp\App.xaml">
      <Link>Templates\Themes\Desktop\App.xaml</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\Playnite.FullscreenApp\App.xaml">
      <Link>Templates\Themes\Fullscreen\App.xaml</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Templates\Themes\Desktop\Theme.csproj">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Templates\Themes\Desktop\Theme.sln">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\Playnite\Localization\LocSource.xaml">
      <Link>Templates\Themes\LocSource.xaml</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\Playnite.DesktopApp\GlobalResources.xaml">
      <Link>Templates\Themes\Desktop\GlobalResources.xaml</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\Playnite.FullscreenApp\GlobalResources.xaml">
      <Link>Templates\Themes\Fullscreen\GlobalResources.xaml</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Templates\Themes\Fullscreen\Theme.csproj">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Templates\Themes\Fullscreen\Theme.sln">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\..\build\ExtensionsRefIgnoreList.txt">
      <Link>Templates\Extensions\ExtensionsRefIgnoreList.txt</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\Playnite.DesktopApp\ControlGalleryView.xaml">
      <Link>Templates\Themes\Desktop\ControlGalleryView.xaml</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\Playnite.FullscreenApp\ControlGalleryView.xaml">
      <Link>Templates\Themes\Fullscreen\ControlGalleryView.xaml</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\PlayniteSDK\Playnite.SDK.csproj" />
    <ProjectReference Include="..\..\Playnite\Playnite.csproj" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command='xcopy "$(SolutionDir)\Tools\Playnite.Toolbox\Templates\Themes\Changelog" "$(OutDir)\Templates\Themes\Changelog\" /e /y' />
  </Target>
</Project>