using Moq;
using NUnit.Framework;
using Playnite;
using Playnite.Database;
using Playnite.Models;
using Playnite.Providers.Steam;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PlayniteTests.Database
{
    [TestFixture]
    public class GameDatabasePlatformsTests
    {
        private string dbPath = Path.Combine(Playnite.PlayniteTests.TempPath, "platformstest.db");

        [SetUp]
        public void Init()
        {
            FileSystem.DeleteFile(dbPath);
        }

        [Test]
        public void PlatformRemovalTest()
        {
            var db = new GameDatabase(null);
            using (db.OpenDatabase(dbPath))
            {
                var platform = new Platform("Test");
                db.AddPlatform(platform);
                var game = new Game("Test")
                {
                    PlatformId = platform.Id
                };

                db.AddGame(game);
                db.RemovePlatform(platform);
                var dbGame = db.GamesCollection.FindById(game.Id);
                Assert.IsNull(dbGame.PlatformId);                
                CollectionAssert.IsEmpty(db.PlatformsCollection.Find(a => a.Name == "Test"));
            }
        }

        [Test]
        public void PcPlatformAutoAssignTest()
        {
            var libraryGames = new List<IGame>()
            {
                new Game()
                {
                    ProviderId = "testid",
                    Name = "Test Game",
                    Provider = Provider.Steam
                },
                new Game()
                {
                    ProviderId = "testid2",
                    Name = "Test Game 2",
                    Provider = Provider.Steam
                }
            };

            var settings = new Settings();
            settings.SteamSettings.IdSource = SteamIdSource.Name;
            settings.SteamSettings.AccountName = string.Empty;
            var steamLibrary = new Mock<ISteamLibrary>();
            steamLibrary.Setup(oc => oc.GetLibraryGames(settings.SteamSettings)).Returns(libraryGames);

            var db = new GameDatabase(settings, null, steamLibrary.Object, null, null, null);
            using (db.OpenDatabase(dbPath))
            {
                // Remove PC platform first, might get autogenerated with clean DB
                var pl = db.PlatformsCollection.FindOne(a => a.Name == "PC");
                if (pl != null)
                {
                    db.RemovePlatform(pl);
                    Assert.IsNull(db.PlatformsCollection.FindOne(a => a.Name == "PC"));
                }

                db.UpdateOwnedGames(Provider.Steam);
                var pcPlatform = db.PlatformsCollection.FindOne(a => a.Name == "PC");
                Assert.IsNotNull(pcPlatform);

                var games = db.GamesCollection.FindAll().ToList();
                Assert.AreEqual(pcPlatform.Id, games[0].PlatformId);
                Assert.AreEqual(pcPlatform.Id, games[1].PlatformId);
            }
        }
    }
}
