name: Bug report
description: Create a report to help us improve
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        **Before creating bug report:**
        - Please use issue search in the repository first. If the bug is something really obvious there's a high change it was already reported.
        - Make sure that the issue is not caused by custom theme or extension. You can restart Playnite in "safe mode" from help menu to quickly test it.
        - Check list of known issues https://github.com/JosefNemec/Playnite/wiki/Known-Issues
        
        **Integration issues**
        If an issue is related to library integrations, use separate [extensions repository](https://github.com/JosefNemec/PlayniteExtensions) to file a report.
  - type: checkboxes
    id: cbDuplicate
    attributes:
      label: Not a duplicate issue
      description: Issue is **not a duplicate** of another [open issue](https://github.com/JosefNemec/Playnite/issues?q=is%3Aopen+is%3Aissue) or [closed issue](https://github.com/JosefNemec/Playnite/issues?q=is%3Aissue+is%3Aclosed)
      options:
        - label: I confirm that I have searched existing issues and that it's not a duplicate
          required: true
  - type: checkboxes
    id: cbNotExtension
    attributes:
      label: Not an extension issue
      description: By submitting this issue, you confirm this issue is about Playnite core functionality and not of an extension
      options:
        - label: I confirm that this issue **IS NOT** about about a library plugin or any kind of extension. I am aware that issues with extensions do not belong in this repository.
          required: true
  - type: checkboxes
    id: cbReadInfo
    attributes:
      label: Instructions read
      description: By submitting this issue, you confirm that you have read the instructions carefully
      options:
        - label: I confirm that I have read the instructions carefully
          required: true
  - type: textarea
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: If it''s not clear from the description how to reproduce the issue please add clear steps to reproduce the behavior.
    validations:
      required: false
  - type: input
    attributes:
      label: Diagnostics ID
      description: 'Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.'      
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
