<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <AssemblyName>Playnite.Deps</AssemblyName>
    <PackageId>Playnite.Deps</PackageId>
    <Version>10.56</Version>
    <Copyright>Copyright © Josef Nemec 2026 onwards</Copyright>
    <Description>Playnite binary dependencies.</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Update="include\**">
      <Pack>true</Pack>
      <PackagePath>lib\net462\%(Filename)%(Extension)</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="include_native_x86\**">
      <Pack>true</Pack>
      <PackagePath>runtimes\win-x86\native\%(Filename)%(Extension)</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </None>
  </ItemGroup>
</Project>
